baseURL = "https://realcoopstories.org/"
languageCode = "en-us"
title = "Real Co-op Stories"

[author]
  name = "Ana Ulin"
  email = "ana@ulin.org"

[permalinks]
  episode = "/:filename/"

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  subtitle = "Conversations with practitioners from the cooperative economy."
  summary = "Cooperative workers tell their stories, along the way answering questions like: How is the day-to-day in a co-op? How did you get started? How did you find others to start something with? Did you get initial funding? How do you make decisions? How does it compare to non-cooperative work? What challenges have you faced?"
  logo = "https://realcoopstories.org/img/real-coop-stories-logo.jpg"
