baseURL = "https://realcoopstories.org/"
languageCode = "en-us"
title = "Real Co-op Stories"

[author]
  name = "Ana Ulin"
  email = "ana@ulin.org"

[permalinks]
  episode = "/:filename/"

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  description = "Conversations with practitioners from the cooperative economy."
  logo = "https://realcoopstories.org/img/real-coop-stories-logo.jpg"
